const $main = $('main')
const $navButton = $('#nav-button')
const $navElements = $('.nav-elements')
const $aboutMeButton = $('#about-me-button')
const $contactFormButton = $('#contact-form-button')
const $socialsButton = $('#socials-button')

const $projectButtons = $('.project-buttons')
const $logo = $('#logo')
const $proj1 = $('#proj-1')
const $proj2 = $('#proj-2')
const $proj3 = $('#proj-3')
const $proj4 = $('#proj-4')
const $proj5 = $('#proj-5')
const $proj6 = $('#proj-6')
const $proj7 = $('#proj-7')